(custom-set-faces
    '(default                               ((t ( :foreground "#2E3436" :background "#EDEDED" )  ))
    '(font-lock-button                      ((t ( :foreground "#0066CC" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#204A87"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#204A87"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#F5666D"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#00578E" :bold t               )  ))
    '(font-lock-keyword                     ((t ( :foreground "#A52A2A" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#A020F0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#4E9A06"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#2F8B58" :bold t               )  ))
    '(font-lock-variable-name               ((t ( :foreground "#0084C8" :bold t               )  ))
 )
