(custom-set-faces
    '(default                               ((t ( :foreground "#cccccc" :background "#181a26" )  ))
    '(font-lock-button                      ((t ( :foreground "#00ffff" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#7f7f7f"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#7f7f7f"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#a2cd5a"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#daa520"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#00bfff"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ffd700"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8c8c8c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#93a8c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b0b1a3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#97b098"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aebed8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#b0b0b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#90a890"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2b6da"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9cb6ad"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#deb887"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#98f5ff"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#4eee94"                       )  ))
 )
