(custom-set-faces
    '(default                               ((t ( :foreground "#000000" :background "#ffffff" )  ))
    '(font-lock-button                      ((t ( :foreground "#0072b2" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#009e73" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#009e73" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#d55e00" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#d55e00"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#56b4e9" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#0072b2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#848ea9"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#0072b2" :bold t               )  ))
    '(font-lock-variable-name               ((t ( :foreground "#e69f00" :bold t               )  ))
 )
