(custom-set-faces
    '(default                               ((t ( :foreground "#c8d3f5" :background "#212337" )  ))
    '(font-lock-button                      ((t ( :foreground "#82aaff" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#7a88cf"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#7a88cf"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#ff995e"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#82aaff"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#c099ff"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#86e1fc" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#86e1fc" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#c099ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff995e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#ff98a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b4f9f8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#f989d3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#ffc777"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#82aaff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#77e0c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#86e1fc"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#c3e88d"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#ffc777"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#ff98a4"                       )  ))
 )
