(custom-set-faces
    '(default                               ((t ( :foreground "#f8f8f2" :background "#323f4e" )  ))
    '(font-lock-button                      ((t ( :foreground "#8895a4" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#56687e" :bold t               )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#56687e" :bold t               )  ))
    '(font-lock-constant                    ((t ( :foreground "#985EFF"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#87DFEB"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#f1fa8c" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#92b6f4" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#92b6f4" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#92b6f4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#BD99FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#53e2ae"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#8897f4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#a1efd3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#92b6f4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#BD99FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#53e2ae"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8897f4"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#f48fb1"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#79e6f3"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#e7c7f1"                       )  ))
 )
