(custom-set-faces
    '(default                               ((t ( :foreground "#c6c6c6" :background "#282b33" )  ))
    '(font-lock-button                      ((t ( :foreground "#819cd6" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6e7899"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6e7899"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#a6c1e0"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#7ebebd"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#819cd6"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#819cd6" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#819cd6" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#819cd6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#a6c1e0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#5b94ab"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b0a2e7"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#7ebebd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#819cd6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#a6c1e0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#5b94ab"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b0a2e7"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#5b94ab"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#b0a2e7"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#a6c1e0"                       )  ))
 )
