(custom-set-faces
    '(default                               ((t ( :foreground "#d4d4d4" :background "#1e1e1e" )  ))
    '(font-lock-button                      ((t ( :foreground "#237AD3" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#579C4C"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#579C4C"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#339CDB"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#D9DAA2"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#339CDB"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#85DDFF" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#85DDFF" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#C586C0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#DB8E73"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#579C4C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#85DDFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#BB80B3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#D7BA7D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#339CDB"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#35CDAF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#207FA1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#DB8E73"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#35CDAF"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#85DDFF"                       )  ))
 )
