(custom-set-faces
    '(default                               ((t ( :foreground "#D8DEE9" :background "#1B2B34" )  ))
    '(font-lock-button                      ((t ( :foreground "#FAC863" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#65737E"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#65737E"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#F99157"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#6699CC"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#C594C5"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#5FB3B3" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#5FB3B3" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#6699CC"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#E27E8D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#99C794"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#C594C5"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#5FB3B3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6699CC"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#E27E8D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#99C794"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#C594C5"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#99C794"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#FAC863"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#F99157"                       )  ))
 )
