(custom-set-faces
    '(default                               ((t ( :foreground "#CEDBE5" :background "#0D0E16" )  ))
    '(font-lock-button                      ((t ( :foreground "#D85F00" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#767676" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#767676" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#8041D8"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#D8B941"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#D83441"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#3679D8" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#3679D8" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#3679D8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#8041D8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#79D836"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#AB11D8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#2D9574"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#3679D8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#8041D8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#79D836"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#AB11D8"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#79D836"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#3679D8"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#86e7d7"                       )  ))
 )
