(custom-set-faces
    '(default                               ((t ( :foreground "#e3e9fa" :background "#2d2b55" )  ))
    '(font-lock-button                      ((t ( :foreground "#82aaff" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#b362ff"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#b362ff"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#fb94ff"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#fad726"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ff9d00"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff9d00" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff9d00" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#ff9d00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff9d00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#ff98a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#ff628c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#f989d3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#fad000"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#82aaff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#ff628c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9effff"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#a5ff90"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#3ad900"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#37fea1"                       )  ))
 )
