(custom-set-faces
    '(default                               ((t ( :foreground "#FCFCFA" :background "#2D2A2E" )  ))
    '(font-lock-button                      ((t ( :foreground "#FCFCFA" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#727072"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#727072"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#AB9DF2"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#A9DC76"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#FF6188"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#FF6188" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#FF6188" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#AB9DF2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#78DCE8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#FC9867"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#A9DC76"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#AB9DF2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#FFD866"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#78DCE8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A9DC76"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#AB9DF2"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#FFD866"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#78DCE8"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#FCFCFA"                       )  ))
 )
