(custom-set-faces
    '(default                               ((t ( :foreground "#0F1019" :background "#F5F5F9" )  ))
    '(font-lock-button                      ((t ( :foreground "#009B7C" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#4E4E4E" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#4E4E4E" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#AF005F"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#AF8700"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#D70000"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#1F55A0" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#1F55A0" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#1F55A0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#AF005F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#005F00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#8700AF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#009B7C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#1F55A0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#AF005F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#005F00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8700AF"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#005F00"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#1F55A0"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#004651"                       )  ))
 )
