(custom-set-faces
    '(default                               ((t ( :foreground "#EEFFFF" :background "#212121" )  ))
    '(font-lock-button                      ((t ( :foreground "#c792ea" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#626262"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#626262"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#F78C6C"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#82aaff"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#89DDFF"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#89DDFF" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#89DDFF" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#c792ea"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#F78C6C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#c3e88d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#89DDFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#bb80b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#ffcb6b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#82aaff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#44b9b1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#80cbc4"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#c3e88d"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#c792ea"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#ffcb6b"                       )  ))
 )
