(custom-set-faces
    '(default                               ((t ( :foreground "#a9b1d6" :background "#1a1b26" )  ))
    '(font-lock-button                      ((t ( :foreground "#b4f9f8" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#51587a"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#51587a"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#ff9e64"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#7aa2f7"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#bb9af7"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#7dcfff" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#7dcfff" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#a9b1d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7aa2f7"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#ff9e64"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#73daca"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#b4f9f8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#e0af68"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#2ac3de"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#73daca"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9aa5ce"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#9ece6a"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#c0caf5"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#c0caf5"                       )  ))
 )
