(custom-set-faces
    '(default                               ((t ( :foreground "#282828" :background "#fbf1c7" )  ))
    '(font-lock-button                      ((t ( :foreground "#a89984" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#a89984"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#a89984"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#8f3f71"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#b57614"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#9d0006"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#076678" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#076678" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#076678"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#b16286"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#8ec07c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#d65d0e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#076678"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#8ec07c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#79740e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8f3f71"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#79740e"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#8f3f71"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#076678"                       )  ))
 )
