(custom-set-faces
    '(default                               ((t ( :foreground "#fff1f3" :background "#2c2525" )  ))
    '(font-lock-button                      ((t ( :foreground "#f9cc6c" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#72696a"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#72696a"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#a8a9eb"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#adda78"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#85dacc"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#fd6883" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#fd6883" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#fd6883"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#f38d70"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#adda78"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#85dacc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#fd6883"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#f38d70"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#adda78"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#adda78"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a8a9eb"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#f9cc6c"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#85dacc"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#fff1f3"                       )  ))
 )
