(custom-set-faces
    '(default                               ((t ( :foreground "#c2c2b0" :background "#171717" )  ))
    '(font-lock-button                      ((t ( :foreground "#87ceeb" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#686858"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#686858"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#578F8F"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#faf4c6"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#87AFD7"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#719611" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#719611" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#528b8b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#578F8F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#6688aa"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#87875f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#8181a6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#87875f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#ff9800"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#87875f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8181a6"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#87875f"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#8181a6"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#faf4c6"                       )  ))
 )
