(custom-set-faces
    '(default                               ((t ( :foreground "#FAFFF6" :background "#172030" )  ))
    '(font-lock-button                      ((t ( :foreground "#B16E75" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#64727d" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#64727d" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#c6797e"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#F9B5AC"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#b18bb1" :slant italic         )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#b18bb1" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#b18bb1" :slant italic         )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#6e94b9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#b18bb1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#A3B09A"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#5D80AE"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#7ea9a9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6e94b9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#b18bb1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A3B09A"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#5D80AE"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#A3B09A"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#c6797e"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#c6797e"                       )  ))
 )
