(custom-set-faces
    '(default                               ((t ( :foreground "#d4d4d4" :background "#191919" )  ))
    '(font-lock-button                      ((t ( :foreground "#FFFFFF" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6D6D6D"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6D6D6D"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#FC9354"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#8CDAFF"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#FF5E5E"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#FF5E5E" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#FF5E5E" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#C586C0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#FC9354"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#468800"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#85DDFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#BB80B3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#E9FDAC"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#8CDAFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#35CDAF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#207FA1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#FBE3BF"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#E9FDAC"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#E9FDAC"                       )  ))
 )
