(custom-set-faces
    '(default                               ((t ( :foreground "#2a2a2a" :background "#fafafa" )  ))
    '(font-lock-button                      ((t ( :foreground "#3b6ea8" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#b1b1b1"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#b1b1b1"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#97365b"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#29838d"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#3b6ea8"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#3b6ea8" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#3b6ea8" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#3b6ea8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#97365b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#4f894c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#842879"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#29838d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#3b6ea8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#97365b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#4f894c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#842879"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#4f894c"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#9a7500"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#cb9aad"                       )  ))
 )
