(custom-set-faces
    '(default                               ((t ( :foreground "#f9f9f9" :background "#282a36" )  ))
    '(font-lock-button                      ((t ( :foreground "#57c7ff" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#606580"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#606580"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#5af78e"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#57c7ff"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ffb86c"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff6ac1" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff6ac1" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#57c7ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff6ac1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#5af78e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#bd93f9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aad4d3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#57c7ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#ff6ac1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#5af78e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#bd93f9"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#f3f99d"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#9aedfe"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#ff5c57"                       )  ))
 )
