(custom-set-faces
    '(default                               ((t ( :foreground "#f8f8f2" :background "#282a36" )  ))
    '(font-lock-button                      ((t ( :foreground "#bd93f9" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6272a4"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6272a4"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#8be9fd"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#50fa7b"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ff79c6"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#bd93f9" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#bd93f9" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#61bfff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff79c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#50fa7b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#bd93f9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#0189cc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#61bfff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#ff79c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#50fa7b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#bd93f9"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#f1fa8c"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#bd93f9"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#ffc9e8"                       )  ))
 )
