(custom-set-faces
    '(default                               ((t ( :foreground "#f6f3e8" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#96CBFE" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#99CC99"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#FFD2A7"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#96CBFE"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ffffff" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ffffff" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#96CBFE"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#FF73FD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#A8FF60"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#00A0A0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#96CBFE"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#FF73FD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A8FF60"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#A8FF60"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#FFFFB6"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#ffabfd"                       )  ))
 )
