(custom-set-faces
    '(default                               ((t ( :foreground "#c5d4dd" :background "#3c4c55" )  ))
    '(font-lock-button                      ((t ( :foreground "#7FC1CA" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#899BA6"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#899BA6"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#7FC1CA"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#83AFE5"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#9A93E1"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#A8CE93" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#A8CE93" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#9A93E1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#83AFE5"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#F2C38F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#A8CE93"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#D18EC2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#DADA93"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#95BEBC"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A8CE93"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9A93E1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#7FC1CA"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#A8CE93"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#DF8C8C"                       )  ))
 )
