(custom-set-faces
    '(default                               ((t ( :foreground "#f2f3f7" :background "#0c0a20" )  ))
    '(font-lock-button                      ((t ( :foreground "#1ea8fc" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#546A90"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#546A90"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#df85ff" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#42c6ff"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ff2afc" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff2afc" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff2afc" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#1ea8fc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff2afc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#a7da1e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#df85ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#A875FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#1ea8fc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#ff2afc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a7da1e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#df85ff"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#7984D1"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#ffd400"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#df85ff"                       )  ))
 )
