(custom-set-faces
    '(default                               ((t ( :foreground "#f8f8f0" :background "#21272e" )  ))
    '(font-lock-button                      ((t ( :foreground "#e74c3c" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#606F73"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#606F73"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#1abc9c"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#e74c3c"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#1abc9c"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#e74c3c" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#e74c3c" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#e74c3c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#53df83"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#1abc9c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#53df83"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#56b5c2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#9cd230"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#56b6c2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#53df83"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#C5A3FF"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#53df83"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#e74c3c"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#f8f8f0"                       )  ))
 )
