(custom-set-faces
    '(default                               ((t ( :foreground "#dddddd" :background "#1b1d1e" )  ))
    '(font-lock-button                      ((t ( :foreground "#fc20bb" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#808080" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#808080" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#60aa00"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#b77fdb" :bold t               )  ))
    '(font-lock-keyword                     ((t ( :foreground "#6c9ef8"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#6c9ef8" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#6c9ef8" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#6c9ef8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#b77fdb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#60aa00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6c9ef8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#b77fdb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#60aa00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#d08928"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#00aa80"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#5699AF"                       )  ))
 )
