(custom-set-faces
    '(default                               ((t ( :foreground "#cbccd1" :background "#1c1d20" )  ))
    '(font-lock-button                      ((t ( :foreground "#fedd38" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#ee7b29"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#fedd38"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ea3d54"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#78bd65" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#78bd65" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#ea3d54"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ee7b29"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#78bd65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#4fb3d8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4fb3d8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#fedd38"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#78bd65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#78bd65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b978ab"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#4fb3d8"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#ee7b29"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#cbccd1"                       )  ))
 )
