(custom-set-faces
    '(default                               ((t ( :foreground "#DCDCDC" :background "#3F3F3F" )  ))
    '(font-lock-button                      ((t ( :foreground "#D0BF8F" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#7F9F7F"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5F7F5F"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#BFEBBF"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#93E0E3"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#F0DFAF" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#8CD0D3" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#8CD0D3" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8CD0D3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#DC8CC3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#7F9F7F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#8CD0D3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#DC8CC3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#7F9F7F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#CC9393"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#7CB8BB"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#DFAF8F"                       )  ))
 )
