(custom-set-faces
    '(default                               ((t ( :foreground "#FFFFFF" :background "#292A30" )  ))
    '(font-lock-button                      ((t ( :foreground "#5DD8FF" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6C7986"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6C7986"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#A167E6"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#41A1C0"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#FC5FA3" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#FD8F3F" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#FD8F3F" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#A167E6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#5DD8FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#FD8F3F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#67B7A4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#D0A8FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#D0BF68"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#59B0CF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#67B7A4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#A167E6"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#FC6A5D"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#5DD8FF"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#41A1C0"                       )  ))
 )
