(custom-set-faces
    '(default                               ((t ( :foreground "#8d9fa1" :background "#002732" )  ))
    '(font-lock-button                      ((t ( :foreground "#3c98e0" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#62787f" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#62787f" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#3c98e0" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#3c98e0"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#93a61a" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#db5823" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#db5823" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#3c98e0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#c49619"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#db5823"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#93a61a"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#3cafa5"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#7a7ed2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#e2468f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#93a61a"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#7a7ed2"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#93a61a"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#c49619" :slant italic         )  ))
    '(font-lock-variable-name               ((t ( :foreground "#8d9fa1"                       )  ))
 )
