(custom-set-faces
    '(default                               ((t ( :foreground "#d7d5d1" :background "#222222" )  ))
    '(font-lock-button                      ((t ( :foreground "#bbbbbb" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#545053" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#545053" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#838083" :slant italic         )  ))
    '(font-lock-function-name               ((t ( :foreground "#d7d5d1" :slant italic         )  ))
    '(font-lock-keyword                     ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#d7d5d1" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#d7d5d1" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#d7d5d1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#838083"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#d7d5d1" :slant italic         )  ))
    '(font-lock-variable-name               ((t ( :foreground "#838083"                       )  ))
 )
