(custom-set-faces
    '(default                               ((t ( :foreground "#FFFFFF" :background "#27212E" )  ))
    '(font-lock-button                      ((t ( :foreground "#EB64B9" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#91889B"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#91889B"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#B381C5"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#EB64B9"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#40B4C4"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#40B4C4" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#40B4C4" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#40B4C4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#EB64B9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#74DFC4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#B381C5"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4D8079"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#40B4C4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#EB64B9"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#74DFC4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#B381C5"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#B4DCE7"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#FFE261"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#FFFFFF"                       )  ))
 )
