(custom-set-faces
    '(default                               ((t ( :foreground "#d6d6d4" :background "#1c1e1f" )  ))
    '(font-lock-button                      ((t ( :foreground "#fd971f" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#555556"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#555556"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#fd971f"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#b6e63e"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#fb2874"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#9c91e4" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#9c91e4" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#fb2874"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#fd971f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b6e63e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#66d9ef"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#fb2874"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#fd971f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#b6e63e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#b6e63e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9c91e4"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#e2c770"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#66d9ef"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#fd971f"                       )  ))
 )
