(custom-set-faces
    '(default                               ((t ( :foreground "#c5c8c6" :background "#1d1f21" )  ))
    '(font-lock-button                      ((t ( :foreground "#81a2be" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#5a5b5a"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5a5b5a"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#de935f"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#81a2be"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#b294bb"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#c5c8c6" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#c5c8c6" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#b294bb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#81a2be"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#de935f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b5bd68"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#c9b4cf"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#f0c674"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#81a2be"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#b5bd68"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b294bb"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#b5bd68"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#f0c674"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#cc6666"                       )  ))
 )
