(custom-set-faces
    '(default                               ((t ( :foreground "#ede0ce" :background "#2b2a27" )  ))
    '(font-lock-button                      ((t ( :foreground "#ff5d38" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5B6268"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#ff5d38"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#bcd42a"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#26a6a6"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff5d38" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff5d38" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#51afef"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#26a6a6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#51afef"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#bcd42a"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#f8f8f0"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#f8f8f0"                       )  ))
 )
