(custom-set-faces
    '(default                               ((t ( :foreground "#839496" :background "#002b36" )  ))
    '(font-lock-button                      ((t ( :foreground "#268bd2" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#405A61"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#405A61"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#d33682" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#268bd2"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#859900" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#cb4b16" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#cb4b16" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#268bd2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#d33682"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#859900"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#6c71c4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#35a69c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#268bd2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#d33682"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#859900"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#6c71c4"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#2aa198"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#b58900"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#6c71c4"                       )  ))
 )
