(custom-set-faces
    '(default                               ((t ( :foreground "#F6F3E8" :background "#171717" )  ))
    '(font-lock-button                      ((t ( :foreground "#8AC6F2" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#656868"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#656868"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#635770"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#EA9847"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#8AC6F2"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#C7B299" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#C7B299" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8AC6F2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#E18Cbb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#86B187"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#BF93C3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#65A399"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#8AC6F2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#E18Cbb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#86B187"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#BF93C3"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#86B187"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#C7B299"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#BF93C3"                       )  ))
 )
