(custom-set-faces
    '(default                               ((t ( :foreground "#5b8512" :background "#1c1408" )  ))
    '(font-lock-button                      ((t ( :foreground "#dbc077" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#707a6a" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#707a6a" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#ff7000"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#ff7000"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ff4e00"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ffbf00" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ffbf00" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#ffbf00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff7000"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#7cb518"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#dbc077"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#d72638"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#0075c4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#5b8512"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#76597b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#ff4e00"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#c5ac6b"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#7cb518"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#7cb518"                       )  ))
 )
