(custom-set-faces
    '(default                               ((t ( :foreground "#bbc2cf" :background "#242730" )  ))
    '(font-lock-button                      ((t ( :foreground "#51afef" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#62686E"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#62686E"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#a991f1"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#5cEfFF"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#51afef"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#C57BDB" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#C57BDB" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#51afef"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#C57BDB"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#7bc275"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a991f1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#51afef"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#C57BDB"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#7bc275"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a991f1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#7bc275"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#FCCE7B"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#DFDFDF"                       )  ))
 )
