(custom-set-faces
    '(default                               ((t ( :foreground "#c0c5ce" :background "#2b303b" )  ))
    '(font-lock-button                      ((t ( :foreground "#D08770" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#65737E"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#65737E"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#D08770"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#8FA1B3"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#b48ead"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#c0c5ce" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#c0c5ce" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8FA1B3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b48ead"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#8FA1B3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b48ead"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#ECBE7B"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#BF616A"                       )  ))
 )
