(custom-set-faces
    '(default                               ((t ( :foreground "#383a42" :background "#fafafa" )  ))
    '(font-lock-button                      ((t ( :foreground "#4078f2" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#9ca0a4"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#9ca0a4"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#b751b6"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#e45649"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#4078f2" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#4078f2" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#4078f2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#50a14f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b751b6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#4078f2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#50a14f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b751b6"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#50a14f"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#986801"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#6a1868"                       )  ))
 )
