(custom-set-faces
    '(default                               ((t ( :foreground "#F8F8F0" :background "#5a5475" )  ))
    '(font-lock-button                      ((t ( :foreground "#C5A3FF" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#E6C000"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#E6C000"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#C5A3FF"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#C2FFDF"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#96CBFE" :slant italic         )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#E6C000" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#E6C000" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#55b3cc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#FFB8D1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#C2FFDF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#C5A3FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#8295D6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#55b3cc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#FFB8D1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#C2FFDF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#C5A3FF"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#FFEA00"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#96CBFE"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#FFB8D1"                       )  ))
 )
