(custom-set-faces
    '(default                               ((t ( :foreground "#cbccc6" :background "#1f2430" )  ))
    '(font-lock-button                      ((t ( :foreground "#ffcc66" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#484f5b"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#484f5b"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#d4bfff"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#ffd580"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ffa759"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#f29e74" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#f29e74" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#73d0ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#d4bfff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#bae67e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#dccbff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#95e6cb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#73d0ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#d4bfff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#bae67e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#dccbff"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#bae67e"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#ffe6b3"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#cbccc6"                       )  ))
 )
