(custom-set-faces
    '(default                               ((t ( :foreground "#605A52" :background "#FCFBF9" )  ))
    '(font-lock-button                      ((t ( :foreground "#7686A9" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#9E9A95" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#9E9A95" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#477A7B"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#605A52" :slant italic         )  ))
    '(font-lock-keyword                     ((t ( :foreground "#83577D"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#886A44" :background "#FCFBF9" )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#886A44" :background "#FCFBF9" )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#98A3BD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#B399AF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#AAAE92"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#B6A48C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#8FAEAD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#98A3BD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#B399AF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#747B4D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#83577D"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#747B4D"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#605A52" :slant italic         )  ))
    '(font-lock-variable-name               ((t ( :foreground "#556995"                       )  ))
 )
