(custom-set-faces
    '(default                               ((t ( :foreground "#3B4252" :background "#E5E9F0" )  ))
    '(font-lock-button                      ((t ( :foreground "#5d86b6" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#8b94a5"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#8b94a5"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#97365B"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#29838D"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#3B6EA8"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#3B6EA8" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#3B6EA8" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#3B6EA8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#97365B"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#4F894C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#842879"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#29838D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#3B6EA8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#97365B"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#4F894C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#842879"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#4F894C"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#9A7500"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#842879"                       )  ))
 )
