(custom-set-faces
    '(default                               ((t ( :foreground "#f2fffc" :background "#273136" )  ))
    '(font-lock-button                      ((t ( :foreground "#ffed72" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6b7678"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6b7678"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#baa0f8"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#a2e57b"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#7cd5f1"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff6d7e" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff6d7e" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#ff6d7e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ffb270"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#a2e57b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#7cd5f1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#ff6d7e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#ffb270"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#a2e57b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2e57b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#baa0f8"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#ffed72"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#7cd5f1"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#f2fffc"                       )  ))
 )
