(custom-set-faces
    '(default                               ((t ( :foreground "#dddddd" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#87afff"                       )  ))
    '(font-lock-comment                     ((t ( :foreground "#686868"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#686868"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#8a8a8a"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#dddddd"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#dddddd"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#8a8a8a" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#8a8a8a" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#448844"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#b22222"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#f8b0b0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#448844"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#b22222"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#f8b0b0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#448844"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#b22222"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#f8b0b0"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#acacac"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#acacac"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#dddddd"                       )  ))
 )
