(custom-set-faces
    '(default                               ((t ( :foreground "#ebdbb2" :background "#282828" )  ))
    '(font-lock-button                      ((t ( :foreground "#8ec07c" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#928374"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#928374"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#d3869b"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#b8bb26"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#fb4934"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ebdbb2" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ebdbb2" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#fe8019"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#cc241d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b8bb26"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#83a598"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#8ec07c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#83a598"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#cc241d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#b8bb26"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#d3869b"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#b8bb26"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#fabd2f"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#83a598"                       )  ))
 )
