(custom-set-faces
    '(default                               ((t ( :foreground "#c7c9cb" :background "#232530" )  ))
    '(font-lock-button                      ((t ( :foreground "#fab795" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#4e5059" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#4e5059" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#f09383"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#87ceeb"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#b877db"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#87ceeb" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#87ceeb" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#21bfc2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#6c6f93"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#09f7a0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b877db"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#87ceeb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#21bfc2"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#6c6f93"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#09f7a0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b877db"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#fab795"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#87ceeb"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#e95678"                       )  ))
 )
