(custom-set-faces
    '(default                               ((t ( :foreground "#CBE3E7" :background "#1E1C31" )  ))
    '(font-lock-button                      ((t ( :foreground "#906CFF" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#565575"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#565575"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#AAFFE4"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#C991E1"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#FF8080"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#63F2F1" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#63F2F1" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#91DDFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#C991E1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#95FFA4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#906CFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#63F2F1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#91DDFF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#C991E1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#95FFA4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#906CFF"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#FFE9AA"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#91DDFF"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#FFE9AA"                       )  ))
 )
