(custom-set-faces
    '(default                               ((t ( :foreground "#eaf2f1" :background "#282a3a" )  ))
    '(font-lock-button                      ((t ( :foreground "#ffd76d" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#696d77"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#696d77"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#c39ac9"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#bad761"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#9cd1bb"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ff657a" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff657a" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#ff657a"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#ff95be"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#bad761"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#9cd1bb"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#ff657a"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#ff95be"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#bad761"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#bad761"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#c39ac9"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#ffd76d"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#9cd1bb"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#eaf2f1"                       )  ))
 )
