(custom-set-faces
    '(default                               ((t ( :foreground "#e6d6ac" :background "#2a2426" )  ))
    '(font-lock-button                      ((t ( :foreground "#87c095" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#5b5b5b"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5b5b5b"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#d3a0bc"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#87c095"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#e68183"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#87c095" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#87c095" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#e68183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#d9bb80"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#87c095"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#e68183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#d9bb80"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#87c095"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#e68183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#87af87"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#d3a0bc"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#87af87"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#d9bb80"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#87c095" :slant italic         )  ))
 )
