(custom-set-faces
    '(default                               ((t ( :foreground "#ECEFF4" :background "#2E3440" )  ))
    '(font-lock-button                      ((t ( :foreground "#81A1C1" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#6f7787"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#6f7787"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#81A1C1"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#88C0D0"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#81A1C1"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#81A1C1" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#81A1C1" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#81A1C1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#B48EAD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#5D80AE"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#8FBCBB"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#81A1C1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#B48EAD"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#5D80AE"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#A3BE8C"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#8FBCBB"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#D8DEE9"                       )  ))
 )
