(custom-set-faces
    '(default                               ((t ( :foreground "#bbc2cf" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#0170bf" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#bbc2cf"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#DFDFDF" :bold t               )  ))
    '(font-lock-keyword                     ((t ( :foreground "#DFDFDF" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#bbc2cf" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#bbc2cf" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#0170bf"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#0170bf"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#98be65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#a9a1e1"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#b4916d"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#DFDFDF" :bold t               )  ))
    '(font-lock-variable-name               ((t ( :foreground "#bbc2cf"                       )  ))
 )
