(custom-set-faces
    '(default                               ((t ( :foreground "#F8F8F2" :background "#272822" )  ))
    '(font-lock-button                      ((t ( :foreground "#FD971F" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#555556" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#555556" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#9C91E4"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#A6E22E"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#F92660"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#F92660" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#F92660" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#F92660"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#FD971F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#A6E22E"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#66D9EF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#F92660"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#FD971F"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#A6E22E"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#A6E22E"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9C91E4"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#E6DB74"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#66D9EF" :slant italic         )  ))
    '(font-lock-variable-name               ((t ( :foreground "#F8F8F2"                       )  ))
 )
