(custom-set-faces
    '(default                               ((t ( :foreground "#605a52" :background "#f7f3ee" )  ))
    '(font-lock-button                      ((t ( :foreground "#7382a0" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#b9a992"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#b9a992"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#465953" :background "#d2ebe3" )  ))
    '(font-lock-function-name               ((t ( :foreground "#605a52"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#614c61" :background "#f1ddf1" )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#605a52" :background "#f7f3ee" )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#605a52" :background "#f7f3ee" )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#7382a0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#9c739c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#81895d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#957f5f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#5f8c7d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#955f5f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#81895d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#81895d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9c739c"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#525643" :background "#e2e9c1" )  ))
    '(font-lock-type                        ((t ( :foreground "#605a52" :background "#f7f3ee" )  ))
    '(font-lock-variable-name               ((t ( :foreground "#4c5361" :background "#dde4f2" )  ))
 )
