(custom-set-faces
    '(default                               ((t ( :foreground "#282a2e" :background "#ffffff" )  ))
    '(font-lock-button                      ((t ( :foreground "#444444" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#c5c8c6" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#c5c8c6" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#969896" :slant italic         )  ))
    '(font-lock-function-name               ((t ( :foreground "#282a2e" :slant italic         )  ))
    '(font-lock-keyword                     ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#282a2e" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#282a2e" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#282a2e"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#969896"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#282a2e" :slant italic         )  ))
    '(font-lock-variable-name               ((t ( :foreground "#969896"                       )  ))
 )
