(custom-set-faces
    '(default                               ((t ( :foreground "#575f66" :background "#fafafa" )  ))
    '(font-lock-button                      ((t ( :foreground "#ff9940" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#c4c7c9"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#c4c7c9"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#a37acc"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#f2ae49"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#fa8d3e"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#ed9366" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ed9366" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#399ee6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#a37acc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#86b300"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b594d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4cbf99"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#399ee6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#a37acc"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#86b300"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b594d6"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#86b300"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#e6ba7e"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#575f66"                       )  ))
 )
