(custom-set-faces
    '(default                               ((t ( :foreground "#f7f1ff" :background "#222222" )  ))
    '(font-lock-button                      ((t ( :foreground "#fce566" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#69676c"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#69676c"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#948ae3"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#7bd88f"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#5ad4e6"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#fc618d" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#fc618d" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#fc618d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#fd9353"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#7bd88f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#5ad4e6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#fc618d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#fd9353"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#7bd88f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#7bd88f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#948ae3"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#fce566"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#5ad4e6"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#f7f1ff"                       )  ))
 )
