(custom-set-faces
    '(default                               ((t ( :foreground "#A0B3C5" :background "#1D252C" )  ))
    '(font-lock-button                      ((t ( :foreground "#5EC4FF" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#41505E"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#41505E"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#E27E8D"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#33CED8"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#5EC4FF"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#5EC4FF" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#5EC4FF" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#5EC4FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#E27E8D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#8BD49C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#B62D65"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#33CED8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#5EC4FF"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#E27E8D"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#8BD49C"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#B62D65"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#539AFC"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#EBBF83"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#718CA1"                       )  ))
 )
