(custom-set-faces
    '(default                               ((t ( :foreground "#383a42" :background "#fafafa" )  ))
    '(font-lock-button                      ((t ( :foreground "#014980" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#556b2f"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#556b2f"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#383a42"                       )  ))
    '(font-lock-function-name               ((t ( :bold t                                     )  ))
    '(font-lock-keyword                     ((t ( :bold t                                     )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#383a42" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#383a42" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#014980"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#556b2f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#b751b6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#4db5bd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#014980"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#556b2f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#b751b6"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#8a3b3c"                       )  ))
    '(font-lock-type                        ((t ( :bold t                                     )  ))
    '(font-lock-variable-name               ((t ( :foreground "#383a42"                       )  ))
 )
