(custom-set-faces
    '(default                               ((t ( :foreground "#4d4d4c" :background "#ffffff" )  ))
    '(font-lock-button                      ((t ( :foreground "#4271ae" :bold t :underline t  )  ))
    '(font-lock-comment                     ((t ( :foreground "#8e908c"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#8e908c"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#f5871f"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#4271ae"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#8959a8"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#4d4d4c" :bold t               )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#4d4d4c" :bold t               )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8959a8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#4271ae"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#718c00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#c678dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#f5871f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#eab700"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#3e999f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#718c00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8959a8"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#718c00"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#bb9200"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#c82829"                       )  ))
 )
