(custom-set-faces
    '(default                               ((t ( :foreground "#333333" :background "#FFFFFF" )  ))
    '(font-lock-button                      ((t ( :foreground "#006DAF" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#8D8D84" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#8D8D84"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#D0372D"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#006699"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#0000FF"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#808080"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388D6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276BA"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80A880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#008000"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#6434A3"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#BA36A5"                       )  ))
 )
