(custom-set-faces
    '(default                               ((t ( :foreground "#cfccd2" :background "#25202a" )  ))
    '(font-lock-button                      ((t ( :foreground "#ff925a" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#767283" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#767283"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#34c8d8"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#ff996f"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ffff0b"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#837f87"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#938e84"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#907733"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#736e84"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#936797"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#738c94"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#a1894f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#7e7a87"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#835787"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#7b8f97"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#ff7fff"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#9fcb66"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#4ac964"                       )  ))
 )
