(custom-set-faces
    '(default                               ((t ( :foreground "#000000" :background "#add8e6" )  ))
    '(font-lock-button                      ((t ( :foreground "#3a5fcd" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#b22222"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#b22222"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#00006DE06DE0"                 )  ))
    '(font-lock-function-name               ((t ( :foreground "#ff0000"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#0000cd"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#b35caf"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#8b008b"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#228b22"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#a0522d"                       )  ))
 )
