(custom-set-faces
    '(default                               ((t ( :foreground "#f5f5f5" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#000000" :background "#bebebe" :bold t :underline t )  ))
    '(font-lock-comment                     ((t ( :foreground "#ff7f24" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#fa8072"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#8470ff" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#00fa9a" :bold t               )  ))
    '(font-lock-keyword                     ((t ( :foreground "#00ffff"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#6495ed" :slant italic         )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8c8c8c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#93a8c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b0b1a3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#97b098"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aebed8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#b0b0b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#90a890"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2b6da"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9cb6ad"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#ffc1c1"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#63b8ff"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#7fffd4"                       )  ))
 )
