(custom-set-faces
    '(default                               ((t ( :foreground "#e1e1e0" :background "#2d3743" )  ))
    '(font-lock-button                      ((t ( :underline t                                )  ))
    '(font-lock-comment                     ((t ( :foreground "#74af68"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#74af68"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#008b8b"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#00ede1" :bold t               )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ffad29" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#23d7d7"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8c8c8c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#93a8c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b0b1a3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#97b098"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aebed8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#b0b0b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#90a890"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2b6da"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9cb6ad"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#e67128"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#34cae2"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#dbdb95"                       )  ))
 )
