(custom-set-faces
    '(default                               ((t ( :foreground "#000000" :background "#ffffff" )  ))
    '(font-lock-button                      ((t ( :foreground "#354fcf" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#595959"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#595959"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#0000b0"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#721045"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#531ab6"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#cd5c5c"                       )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#a0132f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#000000"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#dd22dd"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#008899"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#972500"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#808000"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#531ab6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#008900"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#354fcf"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#8f0075"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#354fcf"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#005f5f"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#005e8b"                       )  ))
 )
