(custom-set-faces
    '(default                               ((t ( :foreground "#ffffff" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#79a8ff" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#dfaf7a"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#dfaf7a"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#00bcff"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#feacd0"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#b6a0ff"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :foreground "#cd5c5c"                       )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#ff7f9f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#fec43f"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#2fafff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#dfaf7a"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#79a8ff"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#d0bc00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#4ae2f0"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#d2b580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#82b0ec"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#caa6df"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#79a8ff"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#6ae4b9"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#00d3d0"                       )  ))
 )
