(custom-set-faces
    '(default                               ((t ( :foreground "#2e3436" :background "#eeeeec" )  ))
    '(font-lock-button                      ((t ( :foreground "#204a87" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#5f615c" :slant italic         )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#5f615c" :slant italic         )  ))
    '(font-lock-constant                    ((t ( :foreground "#204a87" :bold t               )  ))
    '(font-lock-function-name               ((t ( :foreground "#a40000"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#346604"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#75507b"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#5c3566"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#204a87"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#b35000"                       )  ))
 )
