(custom-set-faces
    '(default                               ((t ( :foreground "#383a42" :background "#fafafa" )  ))
    '(font-lock-button                      ((t ( :foreground "#3a5fcd" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#a0a1a7"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#a0a1a7" :bold t               )  ))
    '(font-lock-constant                    ((t ( :foreground "#008b8b"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#0184bc"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#a626a4"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t ( :bold t                                     )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#e44649"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#50a14f"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#c18401"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#8b4513"                       )  ))
 )
