(custom-set-faces
    '(default                               ((t ( :foreground "#f5deb3" :background "#000000" )  ))
    '(font-lock-button                      ((t ( :foreground "#00ffff" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#00cd66"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#00cd66"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#40e0d0"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#98fb98"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#ffffff"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#b0c4de"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8c8c8c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#93a8c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b0b1a3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#97b098"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aebed8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#b0b0b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#90a890"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2b6da"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9cb6ad"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#bdb76b"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#7fffd4"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#9acd32"                       )  ))
 )
