(custom-set-faces
    '(default                               ((t ( :foreground "#000000" :background "#f5f5f5" )  ))
    '(font-lock-button                      ((t ( :foreground "#3a5fcd" :underline t          )  ))
    '(font-lock-comment                     ((t ( :foreground "#7f7f7f"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#7f7f7f"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#6e8b3d"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#cd9b1d"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#1c86ee"                       )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#cdad00"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#707183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#7388d6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#909183"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#709870"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#907373"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#6276ba"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#858580"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#80a880"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#887070"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#8b7355"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#00688b"                       )  ))
    '(font-lock-variable-name               ((t ( :foreground "#2e8b57"                       )  ))
 )
