(custom-set-faces
    '(default                               ((t ( :foreground "#f6f3e8" :background "#242424" )  ))
    '(font-lock-button                      ((t ( :foreground "#f6f3e8" :background "#333333" )  ))
    '(font-lock-comment                     ((t ( :foreground "#99968b"                       )  ))
    '(font-lock-comment-delimiter           ((t ( :foreground "#99968b"                       )  ))
    '(font-lock-constant                    ((t ( :foreground "#e5786d"                       )  ))
    '(font-lock-function-name               ((t ( :foreground "#cae682"                       )  ))
    '(font-lock-keyword                     ((t ( :foreground "#8ac6f2" :bold t               )  ))
    '(font-lock-lsp-face-highlight-textual  ((t ( :foreground "#FFFFFF" :background "#444444" :bold t )  ))
    '(font-lock-negation-char               ((t (                                             )  ))
    '(font-lock-preprocessor                ((t ( :foreground "#e5786d"                       )  ))
    '(font-lock-rainbow-delimiters-depth-1  ((t ( :foreground "#8c8c8c"                       )  ))
    '(font-lock-rainbow-delimiters-depth-2  ((t ( :foreground "#93a8c6"                       )  ))
    '(font-lock-rainbow-delimiters-depth-3  ((t ( :foreground "#b0b1a3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-4  ((t ( :foreground "#97b098"                       )  ))
    '(font-lock-rainbow-delimiters-depth-5  ((t ( :foreground "#aebed8"                       )  ))
    '(font-lock-rainbow-delimiters-depth-6  ((t ( :foreground "#b0b0b3"                       )  ))
    '(font-lock-rainbow-delimiters-depth-7  ((t ( :foreground "#90a890"                       )  ))
    '(font-lock-rainbow-delimiters-depth-8  ((t ( :foreground "#a2b6da"                       )  ))
    '(font-lock-rainbow-delimiters-depth-9  ((t ( :foreground "#9cb6ad"                       )  ))
    '(font-lock-string                      ((t ( :foreground "#95e454"                       )  ))
    '(font-lock-type                        ((t ( :foreground "#92a65e" :bold t               )  ))
    '(font-lock-variable-name               ((t ( :foreground "#cae682"                       )  ))
 )
