#!/bin/bash

original_path="$(pwd -P)"
parent_path="$(cd "$(dirname "${BASH_SOURCE[0]}")"; pwd -P)"

cd "$parent_path"

(cd ../; mkdir -p dataflow-points/build; mkdir -p dataflow-track/build)

(cd ../dataflow-points/build/; cmake .. -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_C_COMPILER="clang"; ninja) >/dev/null

clang++ -I../dataflow-track/src -I../dataflow-track/lib/dataflow -I../dataflow-track/lib/axp/lib/axp -I../dataflow-track/lib/graphviz/graphviz -I../dataflow-track/lib/graphviz/trace -I../dataflow-track/lib/graphviz/hash-table -I../dataflow-track/lib/graphviz/safe-alloc -isystem ../dataflow-track/lib/graphviz/linked-list -isystem ../dataflow-track/lib/graphviz/ansi-colors -isystem ../dataflow-track/lib/graphviz/macro-utils -isystem ../dataflow-track/lib/graphviz/textlib -std=c++2b -fcxx-exceptions -c ../dataflow-track/src/main.cpp -o tmp.o -Xclang -load -Xclang "$(pwd)/../dataflow-points/build/csa-checker.so" -Xclang -add-plugin -Xclang print-vars -fno-elide-constructors -O0 > "points"

(cd ../dataflow-track/build/; cmake .. -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -G Ninja -DCMAKE_CXX_COMPILER="clang++" -DCMAKE_C_COMPILER="clang"; ninja) >/dev/null
../dataflow-track/build/src/dataflow-test > "tracked"

make
./build/translate points tracked | sed 's/:/ /g' > "translated"

echo "-------------  TRACKED   -------------"
cat "tracked"

echo "-------------   POINTS   -------------"
cat "points"

echo "------------- TRANSLATED -------------"
cat "translated"

echo "--------------------------------------"

(cd ../dataflow-visualize; make)
../dataflow-visualize/do "$(pwd)/../dataflow-track/src/main.cpp" translated

mkdir -p "$original_path/site/"
mv main.cpp.html "$original_path/site/index.html"

cp ../dataflow-visualize/anseki-leader-line "$original_path/site/" -r
rm translated tracked points tmp.o -f
